cache:
  pip: true
  timeout: 1000
  directories:
    - tests/spectro

language: python

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      after_success:
        - poetry run codecov
    - python: 3.8
      dist: xenial

notifications:
  email: false

# repo branches to test
branches:
  - py3

before_install:
  - pip install poetry

install:
  - poetry install
  - python tests/download_data.py

script:
  - poetry run pytest
