#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# @Author: José Sánchez-Gallego (gallegoj@uw.edu)
# @Date: 2019-12-28
# @Filename: apo.py
# @License: BSD 3-clause (http://www.opensource.org/licenses/BSD-3-Clause)

# type: ignore


KeysDictionary(
    'apo', (1, 0),
    Key('version',
        String(help='product version')),
    Key('pressure',
        Float(units='inches Hg', strFmt='%.3f', reprFmt='%.3f', invalid='NaN'),
        help='Barometric pressure'),
    Key('windd',
        Float(units='degrees', strFmt='%.1f', reprFmt='%.1f', invalid='NaN'),
        help='Average wind direction'),
    Key('winds',
        Float(units='mph', strFmt='%.1f', reprFmt='%.1f', invalid='NaN'),
        help='Average wind speed'),
    Key('gustd',
        Float(units='degrees', strFmt='%.1f', reprFmt='%.1f', invalid='NaN'),
        help='Average gust direction'),
    Key('gusts',
        Float(units='mph', strFmt='%.1f', reprFmt='%.1f', invalid='NaN'),
        help='Average gust speed'),
    Key('airtemp',
        Float(units='C', strFmt='%.1f', reprFmt='%.1f', invalid='NaN'),
        help='Site air temperature'),
    Key('dewpoint',
        Float(units='C', strFmt='%.1f', reprFmt='%.1f', invalid='NaN'),
        help='Site dewpoint temperature'),
    Key('dpErr',
        String(),
        help='Site hygrothermometer sensor error status'),
    Key('humidity',
        Float(units='%', strFmt='%.1f', reprFmt='%.1f', invalid='NaN'),
        help='Site humidity'),
    Key('dusta',
        Float(units='#/0.1 ft^3', strFmt='%d', reprFmt='%d', invalid='NaN'),
        help='PT outside dust density, 0.3 microns'),
    Key('dustb',
        Float(units='#/0.1 ft^3', strFmt='%d', reprFmt='%d', invalid='NaN'),
        help='PT outside dust density, 1.0 micron'),
    Key('dustc',
        Float(units='#/0.1 ft^3', strFmt='%d', reprFmt='%d', invalid='NaN'),
        help='35m enclosure dust density, 0.3 microns'),
    Key('dustd',
        Float(units='#/0.1 ft^3', strFmt='%d', reprFmt='%d', invalid='NaN'),
        help='35m enclosure dust density, 1.0 micron'),
    Key('windd25m',
        Float(units='degrees', strFmt='%.1f', reprFmt='%.1f', invalid='NaN'),
        help='25m wind direction'),
    Key('winds25m',
        Float(units='mph', strFmt='%.1f', reprFmt='%.1f', invalid='NaN'),
        help='25m wind speed'),
    Key('encl25m',
        Int(units='', strFmt='%d', reprFmt='%d', invalid='NaN'),
        help='25m enclosure position: <0 unknown, 0 closed, >0 open'),
    Key('truss25m',
        Float(units='C', strFmt='%.2f', reprFmt='%.2f', invalid='NaN'),
        help='25m median truss temperature'),
    Key('airTempPT',
        Float(units='C', strFmt='%.1f', reprFmt='%.1f', invalid='NaN'),
        help='PT air temperature'),
    Key('dpTempPT',
        Float(units='C', strFmt='%.1f', reprFmt='%.1f', invalid='NaN'),
        help='PT dewpoint temperature'),
    Key('humidPT',
        Float(units='%', strFmt='%.1f', reprFmt='%.1f', invalid='NaN'),
        help='PT humidity'),
    Key('dimmflux1',
        Float(units='ADU', strFmt='%.1f', reprFmt='%.1f', invalid='NaN'),
        help='DIMM image 1 flux'),
    Key('dimmflux2',
        Float(units='ADU', strFmt='%.1f', reprFmt='%.1f', invalid='NaN'),
        help='DIMM image 2 flux'),
    Key('irscmean',
        Float(units='ADU', strFmt='%.1f', reprFmt='%.1f', invalid='NaN'),
        help='IRSC mean flux'),
    Key('irscsd',
        Float(units='ADU', strFmt='%.1f', reprFmt='%.1f', invalid='NaN'),
        help='IRSC flux standard deviation'),
    Key('diskspace',
        String(name='hostname', help='name of host'),
        String(name='filesystem', help='name of filesystem'),
        Long(name='used', units='bytes', strFmt='%d', reprFmt='%d',
             help='used space', invalid='NaN'),
        Long(name='available', units='bytes', strFmt='%d', reprFmt='%d',
             help='available space', invalid='NaN'),
        help='Disk space information for hostname:filesystem'),
    Key('text', String(), help='text for humans')
)
