name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10']

    env:
      PYTHONPATH: '/home/runner/work/hartmannActor/hartmannActor/actorkeys/python'

    steps:
      - uses: actions/checkout@v3

      - name: Cache Setup
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Cache downloaded files
        uses: actions/cache@v3
        with:
          path: /home/runner/work/hartmannActor/hartmannActor/tests/data/downloaded
          key: ${{ runner.os }}-download-${{ hashFiles('tests/data/files.dat') }}

      - name: Clone actorkeys
        uses: actions/checkout@master
        with:
          repository: sdss/actorkeys
          ref: sdss5
          path: actorkeys

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install .

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          pip install flake8
          flake8 python/hartmann --count --show-source --statistics

      - name: Lint with isort
        run: |
          pip install isort
          isort -c python/hartmann

      - name: Lint with black
        run: |
          pip install black
          black --check python/hartmann
          black --check tests/

      - name: Test with pytest
        run: |
          pip install pytest pytest-mock pytest-asyncio pytest-cov
          python3 tests/download_data.py
          pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
