name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']

    env:
      PYTHONPATH: '/home/runner/work/hartmannActor/hartmannActor/actorkeys/python'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Clone actorkeys
        uses: actions/checkout@master
        with:
          repository: sdss/actorkeys
          ref: sdss5
          path: actorkeys

      - name: Install dependencies
        run: |
          pip install --upgrade wheel pip setuptools
          pip install .

      - name: Lint with ruff
        run: |
          pip install ruff
          ruff check python/hartmann/ tests/

      - name: Lint with black
        run: |
          pip install black
          black --check python/hartmann/ tests/

      - name: Test with pytest
        run: |
          pip install pytest pytest-mock pytest-asyncio pytest-cov
          python3 tests/download_data.py
          pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
